[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_app = "CRXua4uvt4hw6jTcpUZ6VgRymBhM3WZb9GUadz9jLf57"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/chainserver/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
